//! The key bindings, as data (`docs/tui.md`, "Bindings").

use crate::keys::{Edit, Key};
use crate::keyset::{Canon, Contexts};

/// One row of the "Bindings" table, word for word with the code marks
/// dropped.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct Binding {
    /// The key map heading the row shows under.
    pub(crate) area: &'static str,
    /// The action's stable id.
    pub(crate) id: &'static str,
    /// What the action does.
    pub(crate) description: &'static str,
    /// Its keys.
    pub(crate) keys: &'static str,
    /// The condition its Key cell carries, a suffix of `keys`: shown in
    /// parentheses after the action in the key map. Empty when none.
    pub(crate) when: &'static str,
    /// Its other paths: a slash command, a click; empty when none.
    pub(crate) other_paths: &'static str,
    /// The contexts the action acts in.
    pub(crate) contexts: Contexts,
    /// The default key names, in groups of one key per variant in order.
    pub(crate) defaults: &'static [&'static str],
    /// The canonical event per variant.
    pub(crate) events: &'static [Canon],
}

/// Every binding, in the table's order.
pub(crate) const BINDINGS: &[Binding] = &[
    Binding {
        area: "Sessions",
        id: "send",
        when: "",
        description: "Send a prompt, or a steering message during a turn",
        keys: "Enter",
        other_paths: "",
        contexts: Contexts::INPUT,
        defaults: &["enter"],
        events: &[Canon::Key(Key::Enter)],
    },
    Binding {
        area: "Sessions",
        id: "line_break",
        when: "",
        description: "Insert a line break",
        keys: "Shift+Enter",
        other_paths: "Ctrl+J",
        contexts: Contexts::INPUT_STEERING,
        defaults: &["shift+enter", "ctrl+j"],
        events: &[Canon::Edit(Edit::ShiftEnter)],
    },
    Binding {
        area: "Sessions",
        id: "close_or_interrupt",
        when: "",
        description: "Close what is on top; interrupt the turn when nothing is open",
        keys: "Esc",
        other_paths: "click the overlay's ✕ or outside it; click \"Esc to interrupt\"",
        contexts: Contexts::ALL,
        defaults: &["esc"],
        events: &[Canon::Key(Key::Esc)],
    },
    Binding {
        area: "Sessions",
        id: "clear_then_quit",
        when: "twice within about a second on an empty box",
        description: "Clear the draft, then quit",
        keys: "Ctrl+C, twice within about a second on an empty box",
        other_paths: "/quit",
        contexts: Contexts::ALL,
        defaults: &["ctrl+c"],
        events: &[Canon::Key(Key::CtrlC)],
    },
    Binding {
        area: "Sessions",
        id: "go_home",
        when: "",
        description: "Go home",
        keys: "⌥0",
        other_paths: "/home",
        contexts: Contexts::INPUT_STEERING_CONVERSATION,
        defaults: &["alt+0"],
        events: &[Canon::Action],
    },
    Binding {
        area: "Sessions",
        id: "new_session",
        when: "",
        description: "Start a new session",
        keys: "Ctrl+N",
        other_paths: "/new",
        contexts: Contexts::INPUT_STEERING_CONVERSATION,
        defaults: &["ctrl+n"],
        events: &[Canon::Action],
    },
    Binding {
        area: "Sessions",
        id: "rail_row_n",
        when: "",
        description: "Switch to the session of rail card N",
        keys: "⌥1 to ⌥9",
        other_paths: "click the card",
        contexts: Contexts::ALL,
        defaults: &[
            "alt+1", "alt+2", "alt+3", "alt+4", "alt+5", "alt+6", "alt+7", "alt+8", "alt+9",
        ],
        events: &[
            Canon::Key(Key::AltDigit(1)),
            Canon::Key(Key::AltDigit(2)),
            Canon::Key(Key::AltDigit(3)),
            Canon::Key(Key::AltDigit(4)),
            Canon::Key(Key::AltDigit(5)),
            Canon::Key(Key::AltDigit(6)),
            Canon::Key(Key::AltDigit(7)),
            Canon::Key(Key::AltDigit(8)),
            Canon::Key(Key::AltDigit(9)),
        ],
    },
    Binding {
        area: "Sessions",
        id: "delete_session",
        when: "on the row",
        description: "Delete the selected exited session in the session list",
        keys: "Delete, or Backspace, on the row",
        other_paths: "click the row's ✕",
        contexts: Contexts::CONVERSATION,
        defaults: &["delete", "backspace"],
        events: &[Canon::Edit(Edit::Delete)],
    },
    Binding {
        area: "The input box",
        id: "recall_prompt",
        when: "in an empty box",
        description: "Recall an earlier prompt from the project of the session on screen",
        keys: "↑ in an empty box",
        other_paths: "",
        contexts: Contexts::INPUT,
        defaults: &["up"],
        events: &[Canon::Key(Key::Up)],
    },
    Binding {
        area: "The input box",
        id: "search_prompts",
        when: "",
        description: "Search those prompts",
        keys: "Ctrl+R",
        other_paths: "",
        contexts: Contexts::INPUT_STEERING,
        defaults: &["ctrl+r"],
        events: &[Canon::Key(Key::CtrlR)],
    },
    Binding {
        area: "The input box",
        id: "move_word",
        when: "",
        description: "Move by word",
        keys: "⌥← ⌥→, Ctrl+← Ctrl+→",
        other_paths: "",
        contexts: Contexts::INPUT_STEERING,
        defaults: &[
            "alt+left",
            "alt+right",
            "ctrl+left",
            "ctrl+right",
            "alt+b",
            "alt+f",
        ],
        events: &[Canon::Edit(Edit::WordLeft), Canon::Edit(Edit::WordRight)],
    },
    Binding {
        area: "The input box",
        id: "delete_word",
        when: "",
        description: "Delete a word",
        keys: "⌥Backspace",
        other_paths: "",
        contexts: Contexts::INPUT_STEERING,
        defaults: &["alt+backspace"],
        events: &[Canon::Edit(Edit::DeleteWord)],
    },
    Binding {
        area: "The input box",
        id: "line_start_end",
        when: "where the terminal passes them",
        description: "Start or end of the line",
        keys: "⌘← ⌘→, where the terminal passes them",
        other_paths: "",
        contexts: Contexts::INPUT_STEERING,
        defaults: &["super+left", "super+right"],
        events: &[Canon::Edit(Edit::LineStart), Canon::Edit(Edit::LineEnd)],
    },
    Binding {
        area: "The input box",
        id: "open_in_editor",
        when: "",
        description: "Open the draft, or a pasted token, in $VISUAL or $EDITOR",
        keys: "Ctrl+G",
        other_paths: "click the token",
        contexts: Contexts::INPUT_STEERING_CONVERSATION,
        defaults: &["ctrl+g"],
        events: &[Canon::Key(Key::CtrlG)],
    },
    Binding {
        area: "The input box",
        id: "paste_image",
        when: "",
        description: "Paste an image",
        keys: "Ctrl+V",
        other_paths: "",
        contexts: Contexts::INPUT_STEERING,
        defaults: &["ctrl+v"],
        events: &[Canon::Key(Key::CtrlV)],
    },
    Binding {
        area: "The conversation",
        id: "toggle_ledgers",
        when: "",
        description: "Open or close the ledgers",
        keys: "Ctrl+O",
        other_paths: "click a group's line",
        contexts: Contexts::ALL,
        defaults: &["ctrl+o"],
        events: &[Canon::Key(Key::CtrlO)],
    },
    Binding {
        area: "The conversation",
        id: "navigate",
        when: "",
        description: "Move focus from the input box into the conversation",
        keys: "Shift+Tab",
        other_paths: "click an item",
        contexts: Contexts::INPUT_STEERING_CONVERSATION,
        defaults: &["shift+tab"],
        events: &[Canon::Key(Key::BackTab)],
    },
    Binding {
        area: "The conversation",
        id: "focus_next_prev",
        when: "",
        description: "Move focus to the next or previous item",
        keys: "↓ ↑, j k",
        other_paths: "click an item",
        contexts: Contexts::CONVERSATION,
        defaults: &["down", "up", "j", "k"],
        events: &[Canon::Key(Key::Down), Canon::Key(Key::Up)],
    },
    Binding {
        area: "The conversation",
        id: "open_focused",
        when: "",
        description: "Open the focused item",
        keys: "Enter",
        other_paths: "click it",
        contexts: Contexts::CONVERSATION,
        defaults: &["enter"],
        events: &[Canon::Key(Key::Enter)],
    },
    Binding {
        area: "The conversation",
        id: "copy_focused",
        when: "",
        description: "Copy the focused item",
        keys: "y",
        other_paths: "select it",
        contexts: Contexts::CONVERSATION,
        defaults: &["y"],
        events: &[Canon::Key(Key::Char('y'))],
    },
    Binding {
        area: "The conversation",
        id: "focus_area",
        when: "",
        description: "Move focus to the panel, the rail, then the conversation",
        keys: "Tab",
        other_paths: "click the area",
        contexts: Contexts::CONVERSATION,
        defaults: &["tab"],
        events: &[Canon::Key(Key::Tab)],
    },
    Binding {
        area: "The conversation",
        id: "toggle_panel",
        when: "",
        description: "Show or hide the panel",
        keys: "⌥P",
        other_paths: "/panel",
        contexts: Contexts::ALL,
        defaults: &["alt+p"],
        events: &[Canon::Key(Key::AltP)],
    },
    Binding {
        area: "The conversation",
        id: "toggle_rail",
        when: "",
        description: "Show or hide the rail",
        keys: "⌥R",
        other_paths: "drag its edge",
        contexts: Contexts::ALL,
        defaults: &["alt+r"],
        events: &[Canon::Key(Key::AltR)],
    },
    Binding {
        area: "The conversation",
        id: "search",
        when: "where forwarded",
        description: "Search",
        keys: "Ctrl+F; Cmd+F where forwarded",
        other_paths: "",
        contexts: Contexts::INPUT_STEERING_CONVERSATION,
        defaults: &["ctrl+f", "super+f"],
        events: &[Canon::Key(Key::CtrlF)],
    },
    Binding {
        area: "The conversation",
        id: "search_results",
        when: "with search open",
        description: "Open the search results",
        keys: "Ctrl+F with search open",
        other_paths: "click the match count",
        contexts: Contexts::SEARCH,
        defaults: &["ctrl+f", "super+f"],
        events: &[Canon::Key(Key::CtrlF)],
    },
    Binding {
        area: "The conversation",
        id: "search_next_prev",
        when: "with search open",
        description: "Next or previous match",
        keys: "Enter or ↓, Shift+Enter or ↑, with search open",
        other_paths: "",
        contexts: Contexts::SEARCH,
        defaults: &["enter", "shift+enter", "down", "up"],
        events: &[Canon::Key(Key::Down), Canon::Key(Key::Up)],
    },
    Binding {
        area: "The conversation",
        id: "jump_to_end",
        when: "",
        description: "Jump to the end",
        keys: "End",
        other_paths: "click \"↓ New messages below\"",
        contexts: Contexts::ALL,
        defaults: &["end"],
        events: &[Canon::Key(Key::End)],
    },
    Binding {
        area: "Steering",
        id: "select_steering",
        when: "",
        description: "Select a queued steering message",
        keys: "⌥↑ ⌥↓",
        other_paths: "its mouse target",
        contexts: Contexts::INPUT_STEERING_CONVERSATION,
        defaults: &["alt+up", "alt+down"],
        events: &[Canon::Key(Key::AltUp), Canon::Key(Key::AltDown)],
    },
    Binding {
        area: "Steering",
        id: "amend_steering",
        when: "",
        description: "Amend it",
        keys: "Enter",
        other_paths: "its mouse target",
        contexts: Contexts::STEERING,
        defaults: &["enter"],
        events: &[Canon::Key(Key::Enter)],
    },
    Binding {
        area: "Steering",
        id: "drop_steering",
        when: "",
        description: "Drop it",
        keys: "⌥X",
        other_paths: "its mouse target",
        contexts: Contexts::INPUT_STEERING_CONVERSATION,
        defaults: &["alt+x"],
        events: &[Canon::Key(Key::AltX)],
    },
    Binding {
        area: "Requests, models and help",
        id: "next_request",
        when: "",
        description: "Reopen a request put aside, or move to the next, the oldest first, switching to its session",
        keys: "⌥A",
        other_paths: "/approvals; click the badge or a waiting card",
        contexts: Contexts::ALL,
        defaults: &["alt+a"],
        events: &[Canon::Key(Key::AltA)],
    },
    Binding {
        area: "Requests, models and help",
        id: "model_picker",
        when: "",
        description: "Open the model picker",
        keys: "Ctrl+L",
        other_paths: "/model",
        contexts: Contexts::INPUT_STEERING_CONVERSATION,
        defaults: &["ctrl+l"],
        events: &[Canon::Key(Key::CtrlL)],
    },
    Binding {
        area: "Requests, models and help",
        id: "session_only",
        when: "",
        description: "Choose in the model picker for this session only",
        keys: "Ctrl+S",
        other_paths: "",
        contexts: Contexts::PICKER,
        defaults: &["ctrl+s"],
        events: &[Canon::Action],
    },
    Binding {
        area: "Requests, models and help",
        id: "show_all",
        when: "",
        description: "Show every model in the model picker, or only the scoped ones",
        keys: "Tab",
        other_paths: "click \"[show all]\"",
        contexts: Contexts::PICKER,
        defaults: &["tab"],
        events: &[Canon::Key(Key::Tab)],
    },
    Binding {
        area: "Requests, models and help",
        id: "refresh_lists",
        when: "",
        description: "Refresh every model list in the model picker",
        keys: "Ctrl+R",
        other_paths: "click \"⟳ refresh all\"",
        contexts: Contexts::PICKER,
        defaults: &["ctrl+r"],
        events: &[Canon::Key(Key::CtrlR)],
    },
    Binding {
        area: "Requests, models and help",
        id: "key_map",
        when: "",
        description: "Open the key map",
        keys: "F1",
        other_paths: "/? or /help",
        contexts: Contexts::ALL,
        defaults: &["f1"],
        events: &[Canon::Key(Key::F1)],
    },
];

#[cfg(test)]
#[path = "bindings_tests.rs"]
mod tests;
