#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=12

cd "$(dirname "$0")"
ENV_FILE="${ENV_FILE:-/tmp/fiber-tui-check-results.env}"
BIN="$PWD/target/release/tui-prototype"
FIXTURE="$PWD/fixtures/session.jsonl"
CMDS=/tmp/fiber-cmds.jsonl
# The session cut just before the first approval: the last turn runs with a
# queued steering message and nothing open over the input box.
QUEUE_FIXTURE=/tmp/fiber-tui-check-queue.jsonl
GHOSTTY_CONFIG="$HOME/Library/Application Support/com.mitchellh.ghostty/config.ghostty"
MARK="# fiber-tui-check"

# Ghostty config edits sit between two marker lines, and are removed on exit,
# however the wizard ends.
restore_config() {
  [[ -f "$GHOSTTY_CONFIG" ]] || return 0
  grep -q "^$MARK" "$GHOSTTY_CONFIG" || return 0
  sed -i '' "/^$MARK begin/,/^$MARK end/d" "$GHOSTTY_CONFIG"
  printf '  %s✓ restored%s your Ghostty config. Reload it with Cmd+Shift+,\n' "$GREEN" "$RESET"
}
trap restore_config EXIT

add_config() {
  restore_config >/dev/null
  printf '\n%s begin\n%s\n%s end\n' "$MARK" "$1" "$MARK" >> "$GHOSTTY_CONFIG"
  printf '  %s✓ added%s "%s" to %s\n' "$GREEN" "$RESET" "$1" "$GHOSTTY_CONFIG"
  step "Reload Ghostty's config now: Cmd+Shift+, (if a setting seems ignored, open a new window with Cmd+N and run the wizard again from there)."
  pause "Press Enter once it has reloaded."
}

# run_proto ARGS… launches the prototype full screen; Ctrl+C quits it and
# brings the wizard back.
run_proto() {
  pause "Press Enter to launch the prototype. Quit it with Ctrl+C when you are done."
  "$BIN" "${FX:-$FIXTURE}" "$@" || true
}

# verdict KEY "check" records pass, fail or skip and a note for one check.
verdict() {
  local key="$1" label="$2" v="" n=""
  while :; do
    printf '  %s%s%s [p]ass [f]ail [s]kip: ' "$BOLD" "$label" "$RESET"
    read -r v || { v=skip; break; }
    case "$v" in p|P) v=pass; break;; f|F) v=fail; break;; s|S) v=skip; break;; esac
  done
  printf '  %snote (Enter for none):%s ' "$DIM" "$RESET"
  read -r n || true
  write_env "$key" "$v${n:+ — $n}"
}

show_clipboard() {
  say "Your clipboard now holds:"
  printf '%s' "$DIM"; pbpaste | head -n 25 | sed 's/^/    │ /'; printf '%s\n' "$RESET"
}

banner "Fiber TUI prototype: Ghostty checks"

stage "Build and window size"
say "Run this wizard in Ghostty itself, not inside tmux."
[[ -n "${TMUX:-}" ]] && warn "You are inside tmux. Quit tmux and run the wizard again in a plain Ghostty window."
[[ "${TERM_PROGRAM:-}" == "ghostty" ]] || warn "TERM_PROGRAM is '${TERM_PROGRAM:-unset}', not ghostty."
say "Building the release binary…"
cargo build --release -q
printf '  %s✓ built%s %s\n' "$GREEN" "$RESET" "$BIN"
cols=$(tput cols)
if (( cols < 118 )); then
  warn "The window is $cols columns wide. Widen it to at least 118 before going on."
else
  note "The window is $cols columns wide."
fi
say "Results go to $ENV_FILE. Running again keeps them, and Enter keeps a saved note."
pause

stage "Look: stripes, edges, faint text, glimmer"
say "The prototype opens with the whole session loaded and the last turn still running."
step "Stripe: the ▌ on the approval panel at the bottom, and the ▐ on your prompts. Each should be one unbroken bar, with no gap between rows."
step "Edges: on any turn card or panel card, the ▄ and ▀ edges should meet the tint with no seam."
step "Faint text: press Ctrl+O. Tool group summaries and the ledger should be clearly dimmer than replies, but still legible."
step "Glimmer: watch \"Working\" at the bottom. A band sweeps left to right and rests, with no flicker anywhere else."
run_proto --static
verdict STRIPE "Stripes unbroken?"
verdict EDGES "Edges meet the tint?"
verdict FAINT "Faint text dim but legible?"
verdict GLIMMER "Glimmer smooth, no flicker?"

stage "Reduced motion"
step "Watch \"Working\" again. The word should stay still, and only the elapsed seconds change."
run_proto --static --reduced-motion
verdict REDUCED_MOTION "Still word, only seconds change?"

stage "Keyboard detection, Shift+Enter, search"
step "Keys: look at the Session card's \"keys\" line in the side panel. It should say \"kitty · N ms\". Remember N."
step "Shift+Enter: press Ctrl+F, type lock, press Enter twice, then Shift+Enter once. The count should go 1, 2, 3, then back to 2."
step "Search marks: clear the search box, type wait_for_path. Every match is marked, the current one brighter, and collapsed groups with a match open."
run_proto --static
ask KEYS_LINE "What did the keys line say (e.g. kitty · 4 ms, or legacy)?"
write_env KEYS_LINE "$KEYS_LINE"
verdict SHIFT_ENTER "Shift+Enter went back a match?"
verdict SEARCH_MARKS "Matches marked, groups opened?"

stage "Cmd+F"
say "Ghostty binds Cmd+F to its own search. This stage unbinds it for the check, and the wizard removes the line again when it ends."
if confirm "Add 'keybind = super+f=unbind' to your Ghostty config for now?"; then
  add_config "keybind = super+f=unbind"
  step "Press Cmd+F. The prototype's search bar should open in place of the input box."
  run_proto --static
  verdict CMD_F "Cmd+F opened the prototype's search?"
  restore_config
else
  write_env CMD_F "skip — config not changed"
fi

stage "Selection and copy"
step "Selection: drag across a wrapped paragraph of a reply. The highlight follows the mouse and never spills into the side panel."
step "Auto-scroll: drag from mid-conversation up past its top edge and hold still. The view keeps scrolling while the selection grows."
step "Copy: make one last selection across a wrapped paragraph and release. The wizard shows your clipboard afterwards."
step "Shift-drag: hold Shift and drag across the side panel. Ghostty's own selection should take over."
run_proto --static
show_clipboard
verdict SELECTION "Highlight followed, no spill into panel?"
verdict AUTO_SCROLL "Kept scrolling past the edge?"
verdict COPY "Clipboard unwrapped, no margins, stripes or ▄▀?"
verdict SHIFT_DRAG "Shift-drag gave Ghostty's selection?"

stage "Copy through OSC 52 alone"
say "This run pretends to be over SSH, so the prototype copies only through OSC 52 and never runs pbcopy."
printf '' | pbcopy
note "Your clipboard is now empty."
step "Drag across some reply text and release. Ghostty may ask to allow clipboard access; allow it."
pause "Press Enter to launch the prototype. Quit it with Ctrl+C when you are done."
SSH_CONNECTION="fiber-tui-check" "$BIN" "$FIXTURE" --static || true
show_clipboard
verdict OSC52 "Clipboard holds the text?"

stage "Links"
step "Scroll up to the first reply. Hover crates/log/tests/lock.rs and the GitHub URL. Ghostty should underline each."
step "Try a plain click, then Cmd+click, then Cmd+Shift+click, and note which one opens the link."
run_proto --static
ask LINK_GESTURE "Which gesture opened a link (plain, cmd, cmd+shift, none)?"
write_env LINK_GESTURE "$LINK_GESTURE"
verdict LINKS "Underlined on hover and opened?"

stage "⌥ keys, macos-option-as-alt off"
if grep -q '^macos-option-as-alt' "$GHOSTTY_CONFIG" 2>/dev/null; then
  warn "Your config sets macos-option-as-alt already: $(grep '^macos-option-as-alt' "$GHOSTTY_CONFIG")"
fi
awk '/"kind":"permission_requested"/{exit} {print}' "$FIXTURE" > "$QUEUE_FIXTURE"
say "This run uses Ghostty's default, where Option types characters rather than acting as Alt."
note "This session stops before the approval, so nothing covers the input box."
step "With the queued steering message showing above the input box, press ⌥↑. It should load into the input box."
step "Press Esc, then ⌥↑ again, then ⌥X. The message should drop, and a \"would send steer_drop\" row appears."
FX="$QUEUE_FIXTURE" run_proto --static
verdict OPT_DEFAULT "⌥↑ and ⌥X worked with option-as-alt off?"

stage "⌥ keys, macos-option-as-alt on"
if confirm "Add 'macos-option-as-alt = true' to your Ghostty config for now?"; then
  add_config "macos-option-as-alt = true"
  step "Repeat: ⌥↑ loads the queued message, Esc, ⌥↑ again, ⌥X drops it."
  FX="$QUEUE_FIXTURE" run_proto --static
  verdict OPT_ALT "⌥↑ and ⌥X worked with option-as-alt on?"
  restore_config
else
  write_env OPT_ALT "skip — config not changed"
fi

stage "Esc on an approval and in the form"
rm -f "$CMDS"
step "Press Esc straight away. The approval steps aside behind \"1 approval waiting\" and the question form comes up."
step "Click the \"1 approval waiting\" row. The approval comes back. Press Esc again to put it aside."
step "On the form, press Esc. The TUI shows it would send reply declined, then cancel. The turn ends interrupted, and \"declined\" shows under \"you answered\"."
run_proto --static --commands "$CMDS"
say "The prototype would have sent:"
printf '%s' "$DIM"; sed 's/^/    │ /' "$CMDS" 2>/dev/null || note "    (nothing)"; printf '%s\n' "$RESET"
verdict ESC_APPROVAL "Approval stepped aside and came back?"
verdict ESC_FORM "Form Esc sent declined then cancel, turn interrupted?"

stage "Resize"
step "Drag the window narrower than 118 columns. The panel gives way to two status rows under the input box."
step "Drag it wide again. The panel returns, with no garbage left on screen."
run_proto --static
verdict RESIZE "Panel gave way and returned cleanly?"

restore_config
finish
say "Results: $ENV_FILE"
printf '%s' "$DIM"; sed 's/^/    /' "$ENV_FILE"; printf '%s\n' "$RESET"
say "Tell Claude the results are in $ENV_FILE."
