//! `cargo xtask models-dev` against the checked-in snapshot: the drift
//! test regenerates every file in a temporary root and fails when a
//! committed file differs from the generated one.

#![allow(
    clippy::unwrap_used,
    reason = "test code may unwrap (docs/code-quality.md, \"Lints\"); clippy exempts only #[test] functions here"
)]

#[path = "../src/child.rs"]
mod child;
#[path = "../src/test_dir.rs"]
mod test_dir;

use std::os::unix::process::CommandExt as _;
use std::path::Path;
use std::process::{Command, Stdio};
use std::time::Duration;

use child::finished;
use test_dir::TestDir;

/// How long a test waits for one child to exit: generation from the
/// checked-in snapshot is far quicker; this only bounds a hang.
const WITHIN: Duration = Duration::from_secs(30);

/// Every file the generator writes, from the repository root.
const GENERATED: [&str; 7] = [
    "providers/anthropic/providers/anthropic.json",
    "providers/gemini/providers/gemini.json",
    "providers/openai/providers/openai.json",
    "providers/muse/providers/muse.json",
    "providers/opencode/providers/opencode-go.json",
    "providers/opencode/providers/opencode-zen.json",
    "xtask/tests/models-dev.json",
];

/// Where `expected` and `actual` first differ.
struct Difference {
    /// The first differing byte offset.
    offset: usize,
    /// Its 1-based line in the committed text.
    line: usize,
    /// The `"id"` of the model enclosing that line, or "provider-level".
    id: String,
}

/// The first byte where `expected` and `actual` differ; None when they
/// are identical.
fn first_difference(expected: &str, actual: &str) -> Option<Difference> {
    let mut offset = expected
        .bytes()
        .zip(actual.bytes())
        .take_while(|pair| pair.0 == pair.1)
        .count();
    if offset == expected.len() && offset == actual.len() {
        return None;
    }
    while expected.get(..offset).is_none() && offset > 0 {
        offset -= 1;
    }
    let before = expected.get(..offset).unwrap_or("");
    let line = before.bytes().filter(|byte| *byte == b'\n').count() + 1;
    Some(Difference {
        offset,
        line,
        id: enclosing_id(expected, before),
    })
}

/// The value of the nearest `"id": "..."` at or before the difference,
/// or "provider-level" when there is none.
fn enclosing_id(expected: &str, before: &str) -> String {
    match before.rfind("\"id\": \"") {
        None => "provider-level".to_owned(),
        Some(start) => match expected.get(start + 7..).and_then(|rest| rest.find('"')) {
            None => "provider-level".to_owned(),
            Some(end) => expected
                .get(start + 7..start + 7 + end)
                .unwrap_or("provider-level")
                .to_owned(),
        },
    }
}

/// At most 200 bytes of the line holding `offset`.
fn excerpt(text: &str, offset: usize) -> String {
    let before = text.get(..offset.min(text.len())).unwrap_or("");
    let start = before.rfind('\n').map(|index| index + 1).unwrap_or(0);
    let line = text.get(start..).unwrap_or("").lines().next().unwrap_or("");
    let mut end = line.len().min(200);
    while line.get(..end).is_none() && end > 0 {
        end -= 1;
    }
    line.get(..end).unwrap_or("").to_owned()
}

/// One failure message for a file whose committed and generated bytes
/// differ: never a whole file, only the lengths and the first difference.
fn drift_message(path: &str, expected: &str, actual: &str, difference: &Difference) -> String {
    format!(
        "{}: committed {} bytes, generated {} bytes; first difference at byte {} (line {}, {}); committed: {}; generated: {}",
        path,
        expected.len(),
        actual.len(),
        difference.offset,
        difference.line,
        difference.id,
        excerpt(expected, difference.offset),
        excerpt(actual, difference.offset),
    )
}

#[test]
fn first_difference_reports_offset_line_and_model() {
    assert!(first_difference("ab", "ab").is_none());
    let difference = first_difference("x", "y").unwrap();
    assert_eq!(difference.offset, 0);
    assert_eq!(difference.line, 1);
    assert_eq!(difference.id, "provider-level");
    let committed = "{\n  \"models\": [\n    {\"id\": \"a\"},\n    {\"id\": \"b\"}\n  ]\n}\n";
    let generated = committed.replace("\"id\": \"b\"", "\"id\": \"c\"");
    let difference = first_difference(committed, &generated).unwrap();
    assert_eq!(difference.offset, committed.find('b').unwrap());
    assert_eq!(difference.line, 4);
    assert_eq!(difference.id, "b");
    let difference = first_difference("abc", "ab").unwrap();
    assert_eq!((difference.offset, difference.line), (2, 1));
    let difference = first_difference("ab", "abc").unwrap();
    assert_eq!((difference.offset, difference.line), (2, 1));
}

/// Runs the built `cargo xtask models-dev` with `args` in `dir`.
fn models_dev(dir: &TestDir, args: &[&str]) -> (i32, String) {
    let child = Command::new(env!("CARGO_BIN_EXE_xtask"))
        .args(["models-dev"])
        .args(args)
        .current_dir(dir.path())
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .process_group(0)
        .spawn()
        .unwrap();
    let output = finished("xtask models-dev", child, &[], WITHIN);
    let text =
        String::from_utf8(output.stdout).unwrap() + &String::from_utf8(output.stderr).unwrap();
    (output.status.code().unwrap(), text)
}

/// The committed file `path` (from the repository root): through the
/// first-party packages directory, so this file reads one.
fn committed(path: &str) -> String {
    let manifest = Path::new(env!("CARGO_MANIFEST_DIR"));
    let file = match path.strip_prefix("providers/") {
        Some(rest) => manifest.join("../providers").join(rest),
        None => manifest.join(path.strip_prefix("xtask/").unwrap_or(path)),
    };
    std::fs::read_to_string(&file).unwrap()
}

#[test]
fn generated_files_match_the_committed_ones() {
    let dir = TestDir::new("models-dev-drift");
    let snapshot = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/models-dev.json");
    let (code, out) = models_dev(&dir, &["--from", &snapshot.display().to_string()]);
    assert_eq!(code, 0, "{out}");
    let mut failures = Vec::new();
    for path in GENERATED {
        let expected = committed(path);
        let actual = std::fs::read_to_string(dir.path().join(path)).unwrap();
        if let Some(difference) = first_difference(&expected, &actual) {
            failures.push(drift_message(path, &expected, &actual, &difference));
        }
    }
    assert!(failures.is_empty(), "drift:\n{}", failures.join("\n"));
}

#[test]
fn a_missing_from_file_is_an_error_writing_nothing() {
    let dir = TestDir::new("models-dev-missing");
    let missing = dir.path().join("nope.json");
    let (code, out) = models_dev(&dir, &["--from", &missing.display().to_string()]);
    assert_eq!(code, 2, "{out}");
    assert!(out.contains("nope.json"), "{out}");
    assert!(!dir.path().join("providers").exists());
    assert!(!dir.path().join("xtask").exists());
}

#[test]
fn a_catalog_missing_a_source_is_an_error_writing_nothing() {
    let dir = TestDir::new("models-dev-source");
    dir.write("catalog.json", "{\"anthropic\":{\"models\":{}}}");
    let catalog = dir.path().join("catalog.json");
    let (code, out) = models_dev(&dir, &["--from", &catalog.display().to_string()]);
    assert_eq!(code, 2, "{out}");
    assert!(out.contains("models.dev has no `google` provider"), "{out}");
    assert!(!dir.path().join("providers").exists());
    assert!(!dir.path().join("xtask").exists());
}
