[package]
name = "completion-bench"
version = "0.0.0"
edition = "2021"
publish = false

[[bin]]
name = "bin"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
clap_complete = { version = "4", features = ["unstable-dynamic"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
