#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=13

cd "$(dirname "$0")"
ENV_FILE=./fiber-demo-feedback.txt
FIXTURE=fixtures/session.jsonl
HEAVY_FIXTURE=fixtures/large-heavy.jsonl

# rate KEY "label" asks for a 1-5 rating and an optional note, and records
# both as one line in the result file.
rate() {
  local key="$1" label="$2" v="" n=""
  while :; do
    printf '  %s%s%s %s[1-5]:%s ' "$BOLD" "$label" "$RESET" "$DIM" "$RESET"
    read -r v || { v=""; break; }
    case "$v" in 1|2|3|4|5) break ;; esac
    warn "Enter a number from 1 to 5."
  done
  printf '  %snote, anything you want to add (Enter for none):%s ' "$DIM" "$RESET"
  read -r n || true
  write_env "$key" "$v${n:+ — $n}"
}

# show_clipboard prints whatever a system clipboard tool can read back, so
# the person can see what actually got copied.
show_clipboard() {
  say "Here's what's on your clipboard now, if this wizard can read it back:"
  if command -v pbpaste >/dev/null 2>&1; then
    printf '%s' "$DIM"; pbpaste | head -n 20 | sed 's/^/    │ /'; printf '%s\n' "$RESET"
  elif command -v wl-paste >/dev/null 2>&1; then
    printf '%s' "$DIM"; wl-paste 2>/dev/null | head -n 20 | sed 's/^/    │ /'; printf '%s\n' "$RESET"
  elif command -v xclip >/dev/null 2>&1; then
    printf '%s' "$DIM"; xclip -selection clipboard -o 2>/dev/null | head -n 20 | sed 's/^/    │ /'; printf '%s\n' "$RESET"
  else
    note "(no pbpaste, wl-paste or xclip found here — paste it into another app to check)"
  fi
}

# run_demo ARGS… launches the prototype full screen. Quit it with Ctrl+C to
# bring the wizard back.
run_demo() {
  pause "Press Enter to launch the prototype. Quit it with Ctrl+C when you're done looking."
  "$BIN" "$@" || true
}

banner "Fiber TUI prototype: your feedback"

stage "Welcome"
say "This is a throwaway prototype of Fiber's terminal screen. It replays a"
say "recorded session — nothing on your machine talks to a model, and nothing"
say "goes over the network. You'll try a few things, rate each one 1-5, and"
say "at the end this wizard writes one plain-text file you can send back."
uname_s=$(uname -s)
uname_m=$(uname -m)
case "$uname_s $uname_m" in
  "Darwin arm64")   BIN_REL="bin/tui-prototype-macos-arm64" ;;
  "Linux x86_64")   BIN_REL="bin/tui-prototype-linux-x86_64" ;;
  "Linux aarch64")  BIN_REL="bin/tui-prototype-linux-arm64" ;;
  *)
    warn "This demo doesn't have a binary built for $uname_s $uname_m."
    say  "It supports macOS on Apple Silicon, and Linux on x86_64 or arm64."
    say  "Sorry — there's nothing more this wizard can do here."
    exit 1
    ;;
esac
if [[ ! -f "$BIN_REL" ]]; then
  warn "Expected binary not found: $BIN_REL"
  say  "Make sure you're running this from inside the unpacked demo folder."
  exit 1
fi
if [[ "$uname_s" == "Darwin" ]]; then
  xattr -d com.apple.quarantine "$BIN_REL" >/dev/null 2>&1 || true
fi
chmod +x "$BIN_REL"
BIN="$PWD/$BIN_REL"
note "Using $BIN_REL"
pause "Ready to start?"

stage "About your setup"
OS_INFO=$(uname -srm)
write_env OS_INFO "$OS_INFO"
note "OS: $OS_INFO"
TERM_GUESS="${TERM_PROGRAM:-${TERM:-unknown}}"
if [[ -n "$TERM_GUESS" && "$TERM_GUESS" != "unknown" ]] && confirm "Is your terminal '$TERM_GUESS'?"; then
  TERMINAL="$TERM_GUESS"
else
  ask TERMINAL "What terminal are you using (its name is usually in its app menu)?"
fi
write_env TERMINAL "$TERMINAL"
cols=$(tput cols 2>/dev/null || echo 0)
write_env WINDOW_COLS "$cols"
if [[ "$cols" -lt 118 ]]; then
  warn "Your window is $cols columns wide. Widen it to at least 118 columns before going on — the layout needs the room."
else
  note "Window is $cols columns wide. Good."
fi
if [[ -n "${TMUX:-}" ]]; then
  write_env INSIDE_TMUX "yes"
  warn "You're inside tmux. If anything looks broken, try running this in a plain terminal window instead."
else
  write_env INSIDE_TMUX "no"
fi
pause "Press Enter once your window is wide enough."

stage "First look"
say "This loads a whole recorded session at once, already finished streaming in."
step "Look at the overall layout: the conversation on the left, the cards on the right."
step "Look at the colours and how replies, tool calls and cards are marked out."
step "Check that everything is legible at a glance."
run_demo "$FIXTURE" --static
rate FIRST_LOOK "First look: layout, cards, colours, legibility"

stage "Watching it happen live"
say "This one replays the session as it originally happened, streaming in."
step "Watch text stream in as it's \"written\"."
step "Watch the \"Working\" line while a turn is running — it has a small moving glimmer."
run_demo "$FIXTURE"
rate LIVE_REPLAY "Watching the live replay"

stage "Tool groups and the ledger"
say "Tool calls (reading files, running commands, and so on) are grouped."
step "Press Ctrl+O to open every group's ledger of individual calls."
step "Click a group's summary line to open or close just that one."
run_demo "$FIXTURE" --static
rate TOOL_LEDGER "Tool groups and the ledger"

stage "Scrolling"
say "Scroll the conversation and see how it behaves."
step "Scroll up with your mouse wheel or trackpad."
step "While scrolled up, look for a pill telling you there are new messages below — click it, or press End, to jump back to the bottom."
run_demo "$FIXTURE" --static
rate SCROLLING "Scrolling with the wheel or trackpad, and the pill"

stage "Search"
say "Search looks across the whole session."
step "Press Ctrl+F and type a word you can see on screen, such as a filename."
step "Press Enter to jump to the next match, and Shift+Enter for the previous one."
note "In Ghostty, Cmd+F is Ghostty's own search unless it's been unbound — use Ctrl+F if Cmd+F doesn't open the prototype's own search box."
run_demo "$FIXTURE" --static
rate SEARCH "Search: the floating box, and moving between matches"

stage "Select and copy"
say "Text in the conversation can be dragged over and copied, like a normal terminal."
step "Drag over a paragraph of a reply, then release the mouse button."
note "If a link doesn't open with a plain click, your terminal may need a modifier — in Ghostty, try Cmd+Shift+click while mouse capture is on."
run_demo "$FIXTURE" --static
show_clipboard
rate SELECT_COPY "Selecting and copying text"

stage "Approvals and questions"
say "The end of this session has a tool call waiting for approval, then a question form."
step "Press Esc to see the approval step aside, then look at the question form that comes up."
step "Choose an answer and look for the \"would send\" row that shows what would go back."
run_demo "$FIXTURE" --static
rate APPROVAL_FORM "The approval panel and the question form"

stage "The context view"
say "There's a separate view that shows how the session's context is used."
step "Type /context and press Enter to open it."
step "Press Esc to go back to exactly where you were."
run_demo "$FIXTURE" --static
rate CONTEXT_VIEW "The context view"

stage "A narrow window"
say "See how the screen copes with less room."
step "While it's running, shrink the window narrower than 118 columns, then widen it again."
run_demo "$FIXTURE" --static
rate NARROW_WINDOW "How it looks in a narrow window"

stage "A heavy session"
say "This is a much longer, busier recorded session — thousands of lines."
step "Scroll around it, and search for a common word to see how it holds up."
run_demo "$HEAVY_FIXTURE" --static --paged
rate HEAVY_SESSION "The heavy session: scrolling and searching a long one"

stage "A few closing questions"
say "Last thing — three open questions, then one overall rating."
ask Q_BEST "What felt best?"
write_env Q_BEST "$Q_BEST"
ask Q_WORST "What felt worst, or most confusing?"
write_env Q_WORST "$Q_WORST"
ask Q_MISSING "What would you want that's missing?"
write_env Q_MISSING "$Q_MISSING"
rate OVERALL "Overall rating"

_clear
printf '\n%s%s  ✓ All done — thank you%s\n\n' "$BOLD" "$GREEN" "$RESET"
say "Your feedback is saved in:"
printf '  %s%s%s\n\n' "$BOLD" "$PWD/${ENV_FILE#./}" "$RESET"
say "Please send that file back to whoever shared this demo with you."
say "Nothing else on your machine is touched, and nothing was sent anywhere on its own."
