[package]
name = "main"
version = "0.0.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "fiber"
path = "src/main.rs"

[dependencies]
clap.workspace = true
config = { path = "../config" }
contract = { path = "../contract" }
doors = { path = "../doors" }
extensions = { path = "../extensions" }
log = { path = "../log" }
loop = { path = "../loop" }
mcp = { path = "../mcp" }
picture = { path = "../picture" }
provider = { path = "../provider" }
serde_json.workspace = true
tools = { path = "../tools" }

[dev-dependencies]
fakes = { path = "../fakes" }
rustix.workspace = true

[lints]
workspace = true
