[package]
name = "tui"
version = "0.0.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
contract = { path = "../contract" }
ratatui = { version = "0.29", features = ["unstable-rendered-line-info"] }
rustix.workspace = true
serde_json.workspace = true
signal-hook = "0.3"

[dev-dependencies]
fakes = { path = "../fakes" }
insta = "1"

[[example]]
name = "draw"
test = true

[lints]
workspace = true
