#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

REPO="aakshintala/Fiber"
ENVIRONMENT="apple-signing"
ENV_FILE="${HOME}/.config/fiber/apple-signing.env"
mkdir -p "$(dirname "$ENV_FILE")"
chmod 700 "$(dirname "$ENV_FILE")" 2>/dev/null || true

# set_env_secret writes an *environment* secret. release.yml runs the signing
# job in the apple-signing environment, so repository secrets are not visible
# to it and the library's set_secret would put them in the wrong place.
set_env_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" -R "$REPO" --env "$ENVIRONMENT" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s %s secret %s\n' "$GREEN" "$RESET" "$ENVIRONMENT" "$name"
      return
    fi
  fi
  SKIPPED+=("$name — gh secret set $name -R $REPO --env $ENVIRONMENT")
  warn "could not set $name; the summary repeats the command"
}

# expand_path turns a pasted ~/... into a real path, which read does not do.
expand_path() { printf '%s' "${1/#\~/$HOME}"; }

# b64 emits the single-line base64 that sign-and-notarize-macos.sh decodes
# with `openssl base64 -d -A`. Wrapped output would break it.
b64() { openssl base64 -A -in "$1"; }

if [[ "$(uname -s)" != "Darwin" ]]; then
  printf '\n  This wizard exports a certificate from the macOS Keychain.\n'
  printf '  Run it on your Mac.\n\n'
  exit 1
fi

banner "Fiber macOS signing setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Apple Developer: your Team ID"
say "Every signed binary carries your Team ID, and the signing script checks it."
open_url "https://developer.apple.com/account"
step "Sign in, then open Membership details in the sidebar."
step "Copy the Team ID: ten characters, letters and digits."
ask APPLE_TEAM_ID "Paste your Team ID:"
if [[ ! "$APPLE_TEAM_ID" =~ ^[A-Z0-9]{10}$ ]]; then
  warn "that does not look like a Team ID (expected ten characters, A-Z and 0-9)"
  confirm "Use it anyway?" || { say "Re-run when you have it."; exit 1; }
fi
write_env APPLE_TEAM_ID "$APPLE_TEAM_ID"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Developer ID certificate: create or locate"
say "Notarized releases need a Developer ID Application certificate."
say "Skip to the next stage if one is already installed in your login keychain."
open_url "https://developer.apple.com/account/resources/certificates/list"
step "If you already have a 'Developer ID Application' certificate, download it and"
step "double-click the .cer to install it, then continue."
step "Otherwise: Keychain Access > Certificate Assistant > Request a Certificate"
step "From a Certificate Authority, save the CSR to disk, then on the page above"
step "create a new 'Developer ID Application' certificate, upload the CSR,"
step "download the .cer, and double-click it to install."
note "A Developer ID certificate is valid for five years. Re-run this wizard when it expires."
pause "Certificate installed in your login keychain?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Developer ID certificate: identity string"
say "codesign matches the identity by its exact name, so we read it rather than type it."
identities="$(security find-identity -v -p codesigning 2>/dev/null | grep 'Developer ID Application' || true)"
if [[ -z "$identities" ]]; then
  warn "no Developer ID Application identity found in your keychains"
  say "Go back a stage and install the certificate, then re-run."
  exit 1
fi
printf '\n'
printf '%s\n' "$identities" | sed 's/^/    /'
printf '\n'
detected="$(printf '%s\n' "$identities" | head -n1 | sed -n 's/.*"\(Developer ID Application:[^"]*\)".*/\1/p')"
if [[ -n "$detected" ]]; then
  say "Detected: $detected"
  if confirm "Use that identity?"; then
    APPLE_SIGNING_IDENTITY="$detected"
  else
    ask APPLE_SIGNING_IDENTITY "Paste the identity string to use:"
  fi
else
  ask APPLE_SIGNING_IDENTITY "Paste the identity string exactly as shown above:"
fi
write_env APPLE_SIGNING_IDENTITY "$APPLE_SIGNING_IDENTITY"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Developer ID certificate: export for CI"
say "CI needs the certificate and its private key as a password-protected .p12."
step "Open Keychain Access, select the 'login' keychain, then My Certificates."
step "Right-click '$APPLE_SIGNING_IDENTITY' and choose Export."
step "Save as Personal Information Exchange (.p12) and set a strong password."
note "The password protects the export only. You will paste it here and it becomes a CI secret."
pause "Exported the .p12?"
ask APPLE_P12_PATH "Path to the exported .p12:"
APPLE_P12_PATH="$(expand_path "$APPLE_P12_PATH")"
if [[ ! -f "$APPLE_P12_PATH" ]]; then
  warn "no file at $APPLE_P12_PATH"
  exit 1
fi
ask_secret APPLE_DEVELOPER_ID_P12_PASSWORD "Password you set on the .p12:"
if openssl pkcs12 -in "$APPLE_P12_PATH" -passin pass:"$APPLE_DEVELOPER_ID_P12_PASSWORD" -nokeys -noout >/dev/null 2>&1; then
  say "Password verified against the .p12."
else
  warn "openssl could not open that .p12 with that password"
  confirm "Continue anyway?" || exit 1
fi
APPLE_DEVELOPER_ID_P12_BASE64="$(b64 "$APPLE_P12_PATH")"
say "Encoded the certificate: ${#APPLE_DEVELOPER_ID_P12_BASE64} base64 characters."
note "Not written to disk. It goes straight to GitHub in a later stage."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "App Store Connect: notarization key"
say "Notarization uses an App Store Connect API key, separate from the certificate."
open_url "https://appstoreconnect.apple.com/access/integrations/api"
step "Open the Team Keys tab and generate a key with the Developer role."
step "Download the .p8 now. Apple allows the download exactly once."
step "Copy the Key ID from the key's row, and the Issuer ID shown above the table."
ask APPLE_NOTARY_KEY_ID "Paste the Key ID:"
ask APPLE_NOTARY_ISSUER_ID "Paste the Issuer ID:"
ask APPLE_P8_PATH "Path to the downloaded .p8:"
APPLE_P8_PATH="$(expand_path "$APPLE_P8_PATH")"
if [[ ! -f "$APPLE_P8_PATH" ]]; then
  warn "no file at $APPLE_P8_PATH"
  exit 1
fi
if ! grep -q 'BEGIN PRIVATE KEY' "$APPLE_P8_PATH"; then
  warn "that file does not look like a PEM private key"
  confirm "Continue anyway?" || exit 1
fi
APPLE_NOTARY_KEY_P8_BASE64="$(b64 "$APPLE_P8_PATH")"
write_env APPLE_NOTARY_KEY_ID "$APPLE_NOTARY_KEY_ID"
write_env APPLE_NOTARY_ISSUER_ID "$APPLE_NOTARY_ISSUER_ID"
note "Keep the .p8 somewhere safe. Apple will not let you download it again."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "GitHub: the apple-signing environment"
say "release.yml runs the signing job in an environment named '$ENVIRONMENT'."
say "It does not exist yet, so the job would fail before reading any secret."
confirm "Create the '$ENVIRONMENT' environment in $REPO?" || { say "Nothing created."; exit 1; }
if gh api -X PUT "repos/$REPO/environments/$ENVIRONMENT" --silent 2>/dev/null; then
  say "Environment '$ENVIRONMENT' exists."
else
  warn "could not create it; you need admin on $REPO"
  SKIPPED+=("create environment — gh api -X PUT repos/$REPO/environments/$ENVIRONMENT")
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "GitHub: write the signing secrets"
say "Writing the five secrets sign-and-notarize-macos.sh requires."
set_env_secret APPLE_DEVELOPER_ID_P12_BASE64 "$APPLE_DEVELOPER_ID_P12_BASE64"
set_env_secret APPLE_DEVELOPER_ID_P12_PASSWORD "$APPLE_DEVELOPER_ID_P12_PASSWORD"
set_env_secret APPLE_NOTARY_KEY_P8_BASE64 "$APPLE_NOTARY_KEY_P8_BASE64"
set_env_secret APPLE_NOTARY_KEY_ID "$APPLE_NOTARY_KEY_ID"
set_env_secret APPLE_NOTARY_ISSUER_ID "$APPLE_NOTARY_ISSUER_ID"

finish

printf '  %sStill required before a macOS release can be signed%s\n\n' "$BOLD" "$RESET"
printf '  The signing script is hardcoded to Vercel and will reject your certificate\n'
printf '  until issue #224 lands. It needs these two values:\n\n'
printf '    Team ID           %s\n' "$APPLE_TEAM_ID"
printf '    Signing identity  %s\n\n' "$APPLE_SIGNING_IDENTITY"
printf '  They are also saved in %s\n' "$ENV_FILE"
printf '  Neither is secret: both appear in any signed binary.\n\n'
printf '  Verify the whole path with a prerelease before a stable tag depends on it.\n'
printf '  The signing job has never run, because release.yml skips prereleases.\n\n'
